# Generated by Django 5.2.14 on 2026-06-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_likes_post_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='saved_by',
        ),
    ]
