# Generated by Django 5.2.14 on 2026-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_controlusers_age_alter_controlusers_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritsep',
            name='name',
            field=models.CharField(default='Ritsep nomi', max_length=200),
        ),
        migrations.AlterField(
            model_name='ritsep',
            name='ritsep',
            field=models.CharField(default='Ritepni kiriting', max_length=200),
        ),
    ]
