# Generated by Django 5.2.14 on 2026-06-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_comment_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ritsep',
            new_name='Post',
        ),
    ]
